domain: 'api.nlib.cc'
app-host: '0.0.0.0'
app-port: 8080
database-path: '/data/NX-DB'
# update-source: 'ghost-land/Nlib-API'
update-source: 'LenochJaaJ/auto-updater-testing'
test: 'hey i am a new setting'

limiter-enabled: true
rate-limit: 5                   # Number of requests
rate-limit-period: 1            # Time period in seconds
